#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2
id = "cloudreve"
name = "Cloudreve"
description.en = "Cloud storage system."
description.fr = "Cloud storage system." 
version = "4.14.1~ynh1"

maintainers = ["otm33GH"]

[upstream]
license = "GPL-3.0-only" # you can see the available licenses identifiers list here: https://spdx.org/licenses/
website = "https://cloudreve.org/"
admindoc = "https://docs.cloudreve.org/"
code = "https://github.com/cloudreve/Cloudreve"


[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true


ldap = false
sso = false

disk = "2000M"
ram.build = "1500M"
ram.runtime = "500M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/cloudreve/cloudreve/releases/download/4.14.1/cloudreve_4.14.1_linux_amd64.tar.gz"
    sha256 = "f8060a8b81c5889cae26da971c4334950fac3b97bb6429936371259874eeab82"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
	allow_email = true
    
    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]

    main.url = "/"
    main.auth_header = false

    [resources.ports]

    [resources.nodejs]
    version = "24"
    [resources.database]
    type = "mysql"
