#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "cloudreve"
name = "Cloudreve"
description.en = "File management and sharing system, supports multiple storage providers"
description.fr = "Système de gestion et de partage de fichiers, prenant en charge plusieurs fournisseurs de stockage"

version = "4.10.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://cloudreve.org/"
demo = "https://demo.cloudreve.org/session"
admindoc = "https://docs.cloudreve.org/en/"
code = "https://github.com/cloudreve/Cloudreve"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "150M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/cloudreve/cloudreve/releases/download/4.15.0/cloudreve_4.15.0_linux_amd64.tar.gz"
    amd64.sha256 = "a22d0ba44f7276fcbaacdf08dcb2bd0c783a5be6fa98d3d4a93a32b7cfda185a"
    arm64.url = "https://github.com/cloudreve/cloudreve/releases/download/4.15.0/cloudreve_4.15.0_linux_arm64.tar.gz"
    arm64.sha256 = "7fcec42286a2ec40f5b6e231f71d8dd8dfc2f64a11ace0937738ed800ec4c365"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*_linux_amd64.tar.gz"
    autoupdate.asset.arm64 = ".*_linux_rm64.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    #[resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "mariadb-server, redis-server"

    [resources.database]
    type = "mysql"
