#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

max_upload_size=50
auth_secret=$(ynh_string_random --length=32)
ynh_app_setting_set --key=auth_secret --value="$auth_secret"

ynh_app_setting_set --key=max_upload_size --value=$max_upload_size

email_smtp_host=$(cat /etc/yunohost/current_host)
email_smtp_user="$app"
email_smtp_password="$mail_pwd"
email_smtp_port=587

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="conf.ini" --destination="$install_dir/conf.ini"

#=================================================
# INSTALLATION
#=================================================

chown -R $app:$app $install_dir

#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_config_add_nginx

ynh_config_add_systemd --service="$app" 

yunohost service add "$app" --description="Cloudreve --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
